### ISSUE TITLE
MSISDN being used as both ObjectProperty and DatatypeProperty

### ISSUE THREAD

**Issue by ajnelson-nist** [casework/CASE-Examples#53]
The [Oresteia example](examples/illustrations/Oresteia/Oresteia.json) has incorrect usage of `observable:MSISDN`.  The usage as of UCO 0.7.0 is for this to be a Datatype property, referring to a Literal value with datatype `xsd:string`.

There was some question on where this incorrect usage originated (Oresteia, or the mobile device and SIM card example), but after a `git blame` dive, the incorrectly-typed line was found to have originated in [this commit](https://github.com/casework/CASE-Examples/commit/ad839e1a637a5dc6bb028e9d9d93024e059a1995).

It's unclear why the example tries to use this property as an object-reference to a `MobileAccount` object.

This needs to be corrected, first in Oresteia, in a manner that preserves original intent, which unfortunately was only documented in the Git history as "Updated mobile account representation."

Once Oresteia's corrected, other places where this error propagated (several of which are on the website) can be revised.

**Comment by ajnelson-nist** [comment]
@cyberinvestigationexpress , you were the author of the originating commit, so it would be helpful if you could advise on how to fix this.

**Comment by cyberinvestigationexpress** [comment]
Representation of IMSI and MSISDN were under discussion. The outcome is that IMSI and MSISDN are represented as strings in MobileAccountFacets.
